less artsy rewrite of app_epath

diff --git a/rel/files/riak-cs-debug b/rel/files/riak-cs-debug
--- a/rel/files/riak-cs-debug
+++ b/rel/files/riak-cs-debug
@@ -23,6 +23,12 @@
 ##
 ## -------------------------------------------------------------------
 
+set +e
+# this is to revert the effect of `set -e`, set by relx-generated code
+# when we are invoked via `riak-cs debug` (otherwise, non-zero exits,
+# which occur normally, will silently cause riak-cs-debug to
+# terminate)
+
 # /bin/sh on Solaris is not a POSIX compatible shell, but /usr/bin/ksh is.
 if [ `uname -s` = 'SunOS' -a "${POSIX_SHELL}" != "true" ]; then
     POSIX_SHELL="true"
@@ -140,8 +146,8 @@ is_relative() {
     fi
 }
 
-RCS_PATH="${RCS_PATH:-$(cd $(dirname "$0")/.. && pwd -P)}"
 PLATFORM_BASE_DIR={{platform_base_dir}}
+PLATFORM_BASE_DIR=${PLATFORM_BASE_DIR:-$(cd $(dirname "$0")/.. && pwd -P)}
 cs_base_dir=$PLATFORM_BASE_DIR
 if is_relative "{{platform_bin_dir}}"; then
     cs_bin_dir="$PLATFORM_BASE_DIR/{{platform_bin_dir}}"
@@ -168,6 +174,8 @@ if is_relative "{{platform_gen_dir}}"; then
 else
     cs_gen_dir="{{platform_gen_dir}}"
 fi
+
+cd $PLATFORM_BASE_DIR
 
 cuttlefish_conf_dir=${cs_gen_dir}/generated.conf
 
@@ -276,24 +284,8 @@ if [ 0 -eq $get_cfgs  -a  1 -eq $get_ssl_certs ]; then
 fi
 
 if [ 0 -ne $(( $get_cfgs + $get_logs + $get_riakcmds + $get_extracmds )) ]; then
-    # Information specific to Riak requested. Need app_epath.sh and must have
-    # valid base and etc paths defined.
 
-    # app_epath.sh provides make_app_epaths and epath functions.
-    # Allow overriding with APP_EPATH
-    if [ -n "$APP_EPATH" ]; then
-        epath_file="$APP_EPATH"
-    else
-        epath_file="${cs_lib_dir}/app_epath.sh"
-    fi
-
-    if [ ! -f "$epath_file" ]; then
-        echoerr "Required file app_epath.sh not found. Expected here:"
-        echoerr "$epath_file"
-        echoerr "See 'riak-cs-debug -h' and manpage for help."
-        exit 1
-    fi
-    . "$epath_file"
+    . $cs_lib_dir/lib.sh
 
     # Allow overriding cs_base_dir and cs_etc_dir from the environment
     if [ -n "$cs_base_dir" ]; then
